In [19]:
import pyodbc
import pandas as pd
import sys
import os
sys.path.append(r'C:\Users\ujay\Desktop\CodeAlpha_DataAnalysis')

from config import SERVER, DATABASE

In [21]:
conn = pyodbc.connect(
    f'DRIVER={{ODBC Driver 17 for SQL Server}};'
    f'SERVER={SERVER};'
    f'DATABASE={DATABASE};'
    f'Trusted_Connection=yes;'
)

print("Connection successful!")

Connection successful!

In [8]:
# Load all tables from SQL Server

orders = pd.read_sql("SELECT * FROM raw.orders", conn)
customers = pd.read_sql("SELECT * FROM raw.customers", conn)
order_items = pd.read_sql("SELECT * FROM raw.order_items", conn)
payments = pd.read_sql("SELECT * FROM raw.order_payments", conn)
reviews = pd.read_sql("SELECT * FROM raw.order_reviews", conn)
products = pd.read_sql("SELECT * FROM raw.products", conn)
sellers = pd.read_sql("SELECT * FROM raw.sellers", conn)
geolocation = pd.read_sql("SELECT * FROM raw.geolocation", conn)
product_category = pd.read_sql("SELECT * FROM raw.product_category_name_translation", conn)

print("orders:", orders.shape)
print("customers:", customers.shape)
print("order_items:", order_items.shape)
print("payments:", payments.shape)
print("reviews:", reviews.shape)
print("products:", products.shape)
print("sellers:", sellers.shape)
print("geolocation:", geolocation.shape)
print("product_category:", product_category.shape)

C:\Users\ujay\AppData\Local\Temp\ipykernel_16208\284396133.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  orders = pd.read_sql("SELECT * FROM raw.orders", conn)
C:\Users\ujay\AppData\Local\Temp\ipykernel_16208\284396133.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customers = pd.read_sql("SELECT * FROM raw.customers", conn)
C:\Users\ujay\AppData\Local\Temp\ipykernel_16208\284396133.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  order_items = pd.read_sql("SELECT * FROM raw.order_items", conn)
C:\Users\ujay\AppData\Local\Temp\ipykernel_16208\284396133.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  payments = pd.read_sql("SELECT * FROM raw.order_payments", conn)
C:\Users\ujay\AppData\Local\Temp\ipykernel_16208\284396133.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  reviews = pd.read_sql("SELECT * FROM raw.order_reviews", conn)
C:\Users\ujay\AppData\Local\Temp\ipykernel_16208\284396133.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  products = pd.read_sql("SELECT * FROM raw.products", conn)
C:\Users\ujay\AppData\Local\Temp\ipykernel_16208\284396133.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  sellers = pd.read_sql("SELECT * FROM raw.sellers", conn)
C:\Users\ujay\AppData\Local\Temp\ipykernel_16208\284396133.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  geolocation = pd.read_sql("SELECT * FROM raw.geolocation", conn)

orders: (99441, 8)
customers: (99441, 5)
order_items: (112650, 7)
payments: (103886, 5)
reviews: (99224, 7)
products: (32951, 9)
sellers: (3095, 4)
geolocation: (1000163, 5)
product_category: (71, 2)

C:\Users\ujay\AppData\Local\Temp\ipykernel_16208\284396133.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  product_category = pd.read_sql("SELECT * FROM raw.product_category_name_translation", conn)

In [9]:
# load the orders table
orders.head(10)

,"""order_id""","""customer_id""","""order_status""","""order_purchase_timestamp""","""order_approved_at""","""order_delivered_carrier_date""","""order_delivered_customer_date""","""order_estimated_delivery_date"""
0,"""6eec08eba397611760a7ccd3cd4aa98b""",c142fd8186cfdd8c1ef9957f24a419fe,delivered,2017-09-06 09:58:22,2017-09-07 10:34:36,2017-09-11 15:43:29,2017-09-12 17:39:56,2017-09-19 00:00:00
1,a3bbe9aebc3d205399f59fadf59e9d42,"""605355966ecff2dee386b804d4929d30""",delivered,2018-07-13 13:19:04,2018-07-13 13:30:25,2018-07-17 13:58:00,2018-07-20 19:03:51,2018-07-31 00:00:00
2,"""97291e812341c4a06c5614415aa9354a""","""587844f18dd724c6865c9067e6d01550""",delivered,2018-04-25 12:03:39,2018-04-25 13:10:39,2018-04-26 10:40:00,2018-05-07 16:56:27,2018-05-21 00:00:00
3,e7d9d1c03c10e6edb7aa4a91581cf871,"""67f2eeff41637d03b7a7dac88c29404f""",delivered,2017-09-24 15:03:45,2017-09-26 03:56:30,2017-09-26 19:24:41,2017-10-04 18:56:01,2017-10-19 00:00:00
4,"""5154e5ccfca219d687ea397ab3b64f34""",f05818797057c484bbb553b2f08702a0,delivered,2017-10-24 21:22:15,2017-10-24 21:35:23,2017-10-25 19:27:55,2017-10-26 16:04:16,2017-11-06 00:00:00

In [10]:
# load the customers
customers.head(10)

,"""customer_id""","""customer_unique_id""","""customer_zip_code_prefix""","""customer_city""","""customer_state"""
0,"""06b8999e2fba1a1fbc88172c00ba8bc7""","""861eff4711a542e4b93843c6dd7febb0""","""14409""",franca,SP
1,"""18955e83d337fd6b2def6b18a428ac77""","""290c77bc529b7ac935b93aa66c333dc3""","""09790""",sao bernardo do campo,SP
2,"""4e7b3e00288586ebd08712fdd0374a03""","""060e732b5b29e8181a18229c7b0b2b5e""","""01151""",sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,"""259dac757896d24d7702b9acbbff3f3c""","""08775""",mogi das cruzes,SP
4,"""4f2d8ab171c80ec8364f7c12e35b23ad""","""345ecd01c38d18a9036ed96c73b8d066""","""13056""",campinas,SP
5,"""879864dab9bc3047522c92c82e1212b8""","""4c93744516667ad3b8f1fb645a3116a4""","""89254""",jaragua do sul,SC
6,fd826e7cf63160e536e0908c76c3f441,addec96d2e059c80c30fe6871d30d177,"""04534""",sao paulo,SP
7,"""5e274e7a0c3809e14aba7ad5aae0d407""","""57b2a98a409812fe9618067b6b8ebe4f""","""35182""",timoteo,MG
8,"""5adf08e34b2e993982a47070956c5c65""","""1175e95fb47ddff9de6b2b06188f7e0d""","""81560""",curitiba,PR
9,"""4b7139f34592b3a31687243a302fa75b""","""9afe194fb833f79e300e37e580171f22""","""30575""",belo horizonte,MG

In [11]:
# load the sellers table
sellers.head(10)

,"""seller_id""","""seller_zip_code_prefix""","""seller_city""","""seller_state"""
0,"""3442f8959a84dea7ee197c632cb2df15""","""13023""",campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,"""13844""",mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,"""20031""",rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,"""04195""",sao paulo,SP
4,"""51a04a8a6bdcb23deccc82b0b80742cf""","""12914""",braganca paulista,SP
5,c240c4061717ac1806ae6ee72be3533b,"""20920""",rio de janeiro,RJ
6,e49c26c3edfa46d227d5121a6b6e4d37,"""55325""",brejao,PE
7,"""1b938a7ec6ac5061a66a3766e0e75f90""","""16304""",penapolis,SP
8,"""768a86e36ad6aae3d03ee3c6433d61df""","""01529""",sao paulo,SP
9,ccc4bbb5f32a6ab2b7066a4130f114e3,"""80310""",curitiba,PR

In [12]:
# load the geolocation table
geolocation.head()

,"""geolocation_zip_code_prefix""","""geolocation_lat""","""geolocation_lng""","""geolocation_city""","""geolocation_state"""
0,"""21330""",-22.884556850683797,-43.36575321440934,rio de janeiro,RJ
1,"""21350""",-22.87369865097064,-43.33693976739164,rio de janeiro,RJ
2,"""21340""",-22.868220205118504,-43.35885781626178,rio de janeiro,RJ
3,"""21321""",-22.90396558673322,-43.34954508964742,rio de janeiro,RJ
4,"""21321""",-22.882927307230748,-43.3698733458077,rio de janeiro,RJ

In [13]:
# load the product table
products.head(10)

,"""product_id""","""product_category_name""","""product_name_lenght""","""product_description_lenght""","""product_photos_qty""","""product_weight_g""","""product_length_cm""","""product_height_cm""","""product_width_cm"""
0,"""1e9e8ef04dbcff4541ed26657ea517e5""",perfumaria,40,287,1,225,16,10,14
1,"""3aa071139cb16b67ca9e5dea641aaa2f""",artes,44,276,1,1000,30,18,20
2,"""96bd76ec8810374ed1b65e291975717f""",esporte_lazer,46,250,1,154,18,9,15
3,cef67bcfe19066a932b7673e239eb23d,bebes,27,261,1,371,26,4,26
4,"""9dc1a7de274444849c219cff195d0b71""",utilidades_domesticas,37,402,4,625,20,17,13
5,"""41d3672d4792049fa1779bb35283ed13""",instrumentos_musicais,60,745,1,200,38,5,11
6,"""732bd381ad09e530fe0a5f457d81becb""",cool_stuff,56,1272,4,18350,70,24,44
7,"""2548af3e6e77a690cf3eb6368e9ab61e""",moveis_decoracao,56,184,2,900,40,8,40
8,"""37cc742be07708b53a98702e77a21a02""",eletrodomesticos,57,163,1,400,27,13,17
9,"""8c92109888e8cdf9d66dc7e463025574""",brinquedos,36,1156,1,600,17,10,12

In [14]:
# load payment table
payments.head()

,"""order_id""","""payment_sequential""","""payment_type""","""payment_installments""","""payment_value"""
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,"""25e8ea4e93396b6fa0d3dd708e76c1bd""",1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,"""42fdf880ba16b47b59251dd489d4441a""",1,credit_card,2,128.45

In [15]:
#  load the order_items table
order_items.head()

,"""order_id""","""order_item_id""","""product_id""","""seller_id""","""shipping_limit_date""","""price""","""freight_value"""
0,"""00010242fe8c5a6d1ba2dd792cb16214""",1,"""4244733e06e7ecb4970a6e2683c13e61""","""48436dade18ac8b2bce089ec2a041202""",2017-09-19 09:45:35,58.90,13.29
1,"""00018f77f2f0320c557190d7a144bdd3""",1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,"""000229ec398224ef6ca0657da4fc703e""",1,c777355d18b72b67abbeef9df44fd0fd,"""5b51032eddd242adc84c38acab88f23d""",2018-01-18 14:48:30,199.00,17.87
3,"""00024acbcdf0a6daa1e931b038114c75""",1,"""7634da152a4610f1595efa32f14722fc""","""9d7a1d34a5052409006425275ba1c2b4""",2018-08-15 10:10:18,12.99,12.79
4,"""00042b26cf59d7ce69dfabb4e55b4fd9""",1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [16]:
# load the product categories table
product_category.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [17]:
# load the reviews table
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,None,None,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,None,None,2018-03-10,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,None,None,2018-02-17,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,None,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,None,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53